### ISSUE TITLE
Hooks for auto update?

### ISSUE THREAD

**Issue by laike9m** [s1ntoneli/AppUpdater#1]
First, thanks for creating AppUpdater!

I'm trying to use it in my app, and want to use periodic check + auto update as my app mostly runs in the background. I'm wondering if it's possible to add some hooks for auto update, similar to the hooks for manual check/update.

For example:
- Finds a new release (with version and some key info, ditto for the following hooks)
- Does not find a new release
- Successfully installs a new release
- Fails to install a new release

**Comment by s1ntoneli** [comment]
Thanks laike.

After considered it, I think these hooks are necessary and easy to implement.

I will schedule it after wrapping up these few days of work. And a PR is also welcome If you want.

**Comment by laike9m** [comment]
Awesome, thanks!

I'm still quite new to Swift, but I can help take a look at the PR once you have it :)

**Comment by s1ntoneli** [comment]
That's good❤️

**Comment by laike9m** [comment]
Just check to see if there's any update, but no rush 😀

**Comment by s1ntoneli** [comment]
> Just check to see if there's any update, but no rush 😀

Just updated, version 0.1.2, see:

https://github.com/s1ntoneli/AppUpdater/commit/11b83c2bb91078b2eba27fb0a12e7a075a64099e

**Comment by laike9m** [comment]
Thanks! Will try to integrate it to my app
